### ISSUE TITLE
[FEA] Port to Dart

### ISSUE THREAD

**Issue by xlotech** [Meigyoku-Thmn/QuickTranslatorRE#1]
Em thấy Flutter có thể dùng đa nền, mà em code còn yếu với bận trên trường nhiều quá nên đánh dấu lại ghi nào anh có thời gian port sang dart thì em tham gia với, về cơ bản thuật toán convert em đọc code C# có nắm sơ qua, duyệt qua max từ trái sang phải theo config, kiểm tra trong từ điển Names và Vietphrase để lấy value có độ dài key dài nhất có thể, sau khi lấy được thì kiểm tra dịch sang trái và dịch sang phải xem đoạn key lấy được có phải dài nhất hay không, còn phần luật nhân thì dùng regex nên em nghĩ sẽ chậm. Em có tham khảo https://github.com/np-nam/chivi và chivi.app nhưng pro quá em không hiểu, theo thuật toán của cái Quick Translate dễ hiểu hơn. Nhưng bên chivi.app phần Editor ngầu hơn, dùng khá là tiện.

<img width="534" alt="Screen Shot 2022-04-14 at 7 40 01 AM" src="https://user-images.githubusercontent.com/103030241/163292450-edb44b0a-0f70-4d70-a87e-982defd0e7c7.png">

**Comment by Meigyoku-Thmn** [comment]
Ban đầu mình dùng tool revert QT tính là để cải thiện nó, tuy mình còn chẳng có nhu cầu convert truyện, mình chỉ muốn dùng QT như một công cụ tra từ điển hàng loạt thôi. Tuy nhiên mình nói thật, code của QT rất nát bạn ạ, code như một cái nồi cám heo hầm bà lằng, chẳng có tí hy vọng gì ở cái thứ code này. Điều tốt nhất bây giờ là viết một tool mới chạy nhanh hơn và hiệu quả hơn, code tốt hơn thôi. Và mình thì muốn để tâm tới những project khác hơn, nên chắc chắn là không có tương lai Dart hay Java gì cho project này hết bạn nhé.

**Comment by xlotech** [comment]
Chắc đến hè em sẽ tự port qua dart để làm app, em lại thấy cách tiếp cận của QT nó có vẻ  dễ hiểu và dễ cài đặt hơn, còn machine learning em chưa được học với em nghĩ chắc khó làm nổi. Nếu dữ liệu của data bên Vietphrase đủ nhiều và phù hợp với thể loại truyện nào đó thì nó dịch hay hơn cả google. Em xin phép đóng issue, cảm ơn anh nghe.
